src/PerformanceTests/Common.Data/Common.Data.projitems
src/PerformanceTests/Common.Data/IProfile.cs
src/PerformanceTests/Common.Data/IProfileExtensionMethods.cs
src/PerformanceTests/NServiceBus5/IProfile.cs
src/PerformanceTests/NServiceBus5/NServiceBus5.csproj
src/PerformanceTests/NServiceBus6/IProfile.cs
src/PerformanceTests/NServiceBus6/NServiceBus6.csproj
src/PerformanceTests/Persistence.V6.RavenDB.V4/RavenDBProfile.cs
src/PerformanceTests/Transport.V5.AzureServiceBus.V6/AzureServiceBusProfile.cs
src/PerformanceTests/Transport.V5.AzureStorageQueues.V6/AzureStorageQueueProfile.cs
src/PerformanceTests/Transport.V5.RabbitMQ.V3/RabbitMQProfile.cs
src/PerformanceTests/Transport.V5.SQLServer.V2/SqlServerProfile.cs
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/AzureServiceBusProfile.cs
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/AzureStorageQueuesProfile.cs
src/PerformanceTests/Transport.V6.RabbitMQ.V4/RabbitMQProfile.cs
src/PerformanceTests/Transport.V6.SQLServer.V3/SqlServerProfile.cs

First looks for the connection string in the environment variables flag, then falls back to config file

Look at environment variables first for connection strings

---

src/SerializerCompatibilityTests/NServiceBus5/JsonSerializerFacade.cs
src/SerializerCompatibilityTests/Tests/CompatibilityTests/TestInfoGenerator.cs

Making Paket iterate all feeds when looking for a matching package

SerializationTests fixes

---

src/PerformanceTests/Common.Data/Scenarios/GatedPublish/GatedPublishRunner.cs
src/PerformanceTests/Common.Data/Scenarios/LoopRunner.cs
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/AzureServiceBusProfile.cs

configure publisher address for asb

Configure event subscription for asb sample

---

src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus5/NServiceBus5.csproj
src/PerformanceTests/NServiceBus6/App.Release.config
src/PerformanceTests/NServiceBus6/NServiceBus6.csproj

Replaces all logging targets in release mode with splunk only.
Connects to #3

Adding transformations to add splunk to release builds

---

src/PerformanceTests/Common.Data/Program.cs
src/PerformanceTests/Common/EnumExtensionMethods.cs
src/PerformanceTests/Common/Permutations/Permutation.cs
src/PerformanceTests/Common/Permutations/PermutationParser.cs
src/PerformanceTests/Common/Utils.csproj
src/PerformanceTests/Common/Variables/Audit.cs
src/PerformanceTests/Common/Variables/DTC.cs
src/PerformanceTests/Common/Variables/IOPS.cs
src/PerformanceTests/Common/Variables/Outbox.cs

Connects to https://github.com/Particular/EndToEnd/issues/3

Added descriptions to enums and a friendly display name

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/IContext.cs
src/PerformanceTests/Common/INeedContext.cs
src/PerformanceTests/Common/IProfileExtensionMethods.cs
src/PerformanceTests/Common/ProfilesExtension.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Common/Scenarios/GatedPublish/GatedPublishRunner.cs
src/PerformanceTests/Distribution.V5.MsmqDistributor.V5/Distribution.V5.MsmqDistributor.V5.csproj
src/PerformanceTests/Distribution.V5.MsmqDistributor.V5/DistributorProfile.cs
src/PerformanceTests/Distribution.V5.MsmqDistributor.V5/packages.config
src/PerformanceTests/Distribution.V6.SenderSide/Distribution.V6.SenderSide.csproj
src/PerformanceTests/Distribution.V6.SenderSide/SenderSideProfile.cs
src/PerformanceTests/Distribution.V6.SenderSide/packages.config
src/PerformanceTests/Distribution.V6.SenderSide/routes.xml
src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/PerformanceTests.sln
src/PerformanceTests/Persistence.V5.RavenDB.V3/RavenDBProfile.cs
src/PerformanceTests/Tests/Categories/DistributorFixture.cs
src/PerformanceTests/Tests/Categories/SenderSideFixture.cs
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Tests/Tools/PermutationDirectoryResolver.cs
src/PerformanceTests/Tests/app.config
src/PerformanceTests/Utils/Permutations/Permutation.cs
src/PerformanceTests/Utils/Permutations/PermutationGenerator.cs
src/PerformanceTests/Utils/Permutations/PermutationParser.cs
src/PerformanceTests/Utils/Permutations/Permutations.cs
src/PerformanceTests/Utils/Utils.csproj
src/PerformanceTests/Utils/Variables/ScaleOut.cs
src/PerformanceTests/routes.xsd

**Please merge #50 first as this branch is forked from *azure-persistence***
Adds distributor and sender-side distribution.

Distribution

---

src/TransportCompatibilityTests/AzureServiceBusV6/AzureServiceBusV6.csproj
src/TransportCompatibilityTests/AzureServiceBusV7/AzureServiceBusV7.csproj
src/TransportCompatibilityTests/AzureStorageQueuesV6/AzureStorageQueuesV6.csproj
src/TransportCompatibilityTests/AzureStorageQueuesV7/AzureStorageQueuesV7.csproj
src/TransportCompatibilityTests/RabbitMQV1/RabbitMQV1.csproj
src/TransportCompatibilityTests/RabbitMQV2/RabbitMQV2.csproj
src/TransportCompatibilityTests/RabbitMQV3/RabbitMQV3.csproj
src/TransportCompatibilityTests/SqlServerV1/SqlServerV1.csproj
src/TransportCompatibilityTests/SqlServerV2/EndpointFacade.cs
src/TransportCompatibilityTests/SqlServerV2/SqlServerV2.csproj
src/TransportCompatibilityTests/SqlServerV2/packages.config
src/TransportCompatibilityTests/SqlServerV3/EndpointFacade.cs
src/TransportCompatibilityTests/SqlServerV3/SqlServerV3.csproj
src/TransportCompatibilityTests/SqlServerV3/packages.config
src/TransportCompatibilityTests/TransportCompatibilityTests.Common/MessageStore.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/AssertExtensions.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/SqlServer/Subscriptions.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/SqlServer/UpgradingV2SubscriberToV3SubscriberWithV3Publisher.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/TransportCompatibilityTests.csproj

Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/181
@SzymonPobiega @johnsimons 
This PR is based on top of #48

Sql server subscriptions

---

src/PerformanceTests/Common/ProfileExtensionMethods.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus6/App.Release.config
src/PerformanceTests/Utils/Statistics.cs

Connects to https://github.com/Particular/EndToEnd/issues/3

Send test name through to splunk for further categorization

---

README.md

@weralabaj @SimonCropp want to help me in making a draft of #4 
Resolve #4

[WIP] Making a stub at README.md file

---

src/TransportCompatibilityTests/AzureStorageQueuesV6/EndpointFacade.cs
src/TransportCompatibilityTests/AzureStorageQueuesV7/AzureStorageQueuesV7.csproj
src/TransportCompatibilityTests/AzureStorageQueuesV7/EndpointFacade.cs
src/TransportCompatibilityTests/AzureStorageQueuesV7/packages.config
src/TransportCompatibilityTests/TransportCompatibilityTests.sln
src/TransportCompatibilityTests/TransportCompatibilityTests/AzureStorageQueues/MessageExchangePatterns.cs

Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/86

Update and fix asq

---

src/PerformanceTests/Common/EnvironmentStats.cs
src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus6/App.Release.config

* Logs additional info about the environment
* Write the 'Environment' logger to Splunk

Logging environment info to Splunk

---

src/PerformanceTests/Persistence.V5.NHibernate.V6/NHibernateProfile.cs
src/PerformanceTests/Persistence.V6.RavenDB.V4/Persistence.V6.RavenDB_v4.csproj
src/PerformanceTests/Persistence.V6.RavenDB.V4/RavenDBPersistenceExtentions.cs
src/PerformanceTests/Persistence.V6.RavenDB.V4/app.config
src/PerformanceTests/Persistence.V6.RavenDB.V4/packages.config
src/PerformanceTests/Tests/app.config

Connects to Particular/PlatformDevelopment#733

Use NServiceBus.RavenDB v4 beta package

---

src/TransportCompatibilityTests/SqlServerV3/SqlServerV3.csproj
src/TransportCompatibilityTests/SqlServerV3/packages.config

Connects to https://github.com/Particular/PlatformDevelopment/issues/732
@Particular/endtoend-maintainers

Sql server updated to 3.0.0-beta001

---

src/PerformanceTests/Transport.V6.SQLServer.V3/Transport.V6.SQLServer_v3.csproj
src/PerformanceTests/Transport.V6.SQLServer.V3/packages.config

As title says, moved from alpha to beta

Upgrade to latest Beta of SQL Server transport

---

src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/Persistence.V6.Azure_v7/AzureProfile.cs
src/PerformanceTests/Persistence.V6.Azure_v7/Persistence.V6.Azure_v7.csproj
src/PerformanceTests/Persistence.V6.Azure_v7/app.config
src/PerformanceTests/Persistence.V6.Azure_v7/packages.config
src/PerformanceTests/Persistence.V6.RavenDB.V4/Persistence.V6.RavenDB_v4.csproj
src/PerformanceTests/Persistence.V6.RavenDB.V4/packages.config
src/PerformanceTests/Tests/app.config
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/AzureServiceBusProfile.cs
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/Transport.V6.AzureServiceBus_v7.csproj
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/Transport.V6.AzureStorageQueues_v7.csproj
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/app.config
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/packages.config

- Implemented Azure persistence for NServiceBus 6.x
- Updated packages
- Downgraded to not have pre-release external dependencies

Implemented Azure Persistence for NServiceBus 6 + Package updates

---

src/TransportCompatibilityTests/SqlServerV3/EndpointFacade.cs
src/TransportCompatibilityTests/SqlServerV3/SqlServerV3.csproj
src/TransportCompatibilityTests/SqlServerV3/packages.config

ping @Particular/endtoend-maintainers

Updating SqlServer to beta002

---

src/PerformanceTests/Common/Program.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Persistence.V5.NHibernate.V6/NHibernateProfile.cs
src/PerformanceTests/Persistence.V5.NHibernate.V6/init.sql
src/PerformanceTests/Persistence.V6.NHibernate.V7/NHibernateProfile.cs
src/PerformanceTests/Persistence.V6.NHibernate.V7/init.sql
src/PerformanceTests/Tests/Categories/SqlTransportFixture.cs
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Tests/Tools/PermutationDirectoryResolver.cs
src/PerformanceTests/Transport.V5.SQLServer.V2/SqlServerProfile.cs
src/PerformanceTests/Transport.V5.SQLServer.V2/init.sql
src/PerformanceTests/Transport.V6.SQLServer.V3/SqlServerProfile.cs
src/PerformanceTests/Transport.V6.SQLServer.V3/init.sql
src/PerformanceTests/Utils/ConfigurationHelper.cs
src/PerformanceTests/Utils/Permutations/PermutationGenerator.cs
src/PerformanceTests/Utils/SqlHelper.cs
src/PerformanceTests/Utils/Variables/Persistence.cs
src/PerformanceTests/Utils/Variables/Transport.cs

A lot of changes to make the performance test project work with SQL Azure. Currently only SQL Transport is tested. NHibernate failed at the start but maybe the current changes already made NHibernate work too.

SQL Azure support / configuration

---

src/PerformanceTests/Tests/Categories/AzureFixture.cs
src/PerformanceTests/Tests/Tests.csproj

Azure explicit fixture to more easily test azure stuff for maintainers

---

src/PerformanceTests/Tests/Categories/Base.cs
src/PerformanceTests/Tests/Categories/TestSessionInitializer.cs
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Tests/Tools/TestEnvironment.cs

Performance tests NUnit 3.x fixes

---

src/NHPersistenceCompatibilityTests/4.5/Persister.cs
src/NHPersistenceCompatibilityTests/5.0/Persister.cs
src/NHPersistenceCompatibilityTests/6.0/Persister.cs
src/NHPersistenceCompatibilityTests/6.1.0/Persister.cs
src/NHPersistenceCompatibilityTests/6.2/Persister.cs
src/NHPersistenceCompatibilityTests/7.0/Persister.cs
src/NHPersistenceCompatibilityTests/Common/IRawPersister.cs
src/NHPersistenceCompatibilityTests/Common/NugetHelper.cs
src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/CompletingSagaTests.cs
src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/PersistenceCompatibilityTests.csproj
src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/Util/PersisterFacade.cs
src/NHPersistenceCompatibilityTests/SharedDefinitions/ObjectFetcher.cs
src/NHPersistenceCompatibilityTests/SharedDefinitions/RawPersister.cs

Connects to Particular/PlatformDevelopment#737

Add Complete testing scenario for NHibernate persister compatibility tests

---

src/PlatformCompatibilityTests/RabbitMQ/RabbitMQ.csproj
src/PlatformCompatibilityTests/RabbitMQ/RabbitMQConventionalRoutingTopologyTransportDetails.cs
src/PlatformCompatibilityTests/RabbitMQ/RabbitMQDirectRoutingTopologyTransportDetails.cs
src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/ServiceControlTest.cs

Connects to https://github.com/Particular/V6Launch/issues/74

[WIP] Rabbit Transport compat tests

---

src/PerformanceTests/Persistence.V5.RavenDB.V3/RavenDBProfile.cs
src/PerformanceTests/Persistence.V6.RavenDB.V4/RavenDBProfile.cs

Fix: #176
cc: @Particular/endtoend-maintainers please review and merge

Changing the Ravendb tests to use environment variable when present

---

src/PerformanceTests/Transport.V6.AzureServiceBus.V7/Transport.V6.AzureServiceBus_v7.csproj
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/Transport.V6.AzureStorageQueues_v7.csproj
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/packages.config

Latest package from Nuget.org for performance tests.

Packages 20160929

---

src/TransportCompatibilityTests/AzureServiceBusV7/AzureServiceBusV7.csproj
src/TransportCompatibilityTests/AzureServiceBusV7/packages.config

@Particular/endtoend-maintainers please review

ASB RC1 update

---

src/TransportCompatibilityTests/SqlServerV3/EndpointFacade.cs
src/TransportCompatibilityTests/SqlServerV3/SqlServerV3.csproj
src/TransportCompatibilityTests/SqlServerV3/packages.config

@Particular/endtoend-maintainers can you please review?

Transport tests updated to newest sqlserver beta0007

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.V5.cs
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.V6.cs
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.cs
src/PerformanceTests/Tests/Categories/Base.cs
src/PerformanceTests/Tests/Categories/PersistersPublishStrategiesFixture.cs
src/PerformanceTests/Tests/Categories/PersistersPublishTransactionModesFixture.cs
src/PerformanceTests/Tests/Tests.csproj

Originated from a discussion with @danielmarbach @andreasohlund @SzymonPobiega and @mikeminutillo about https://github.com/Particular/NServiceBus.NHibernate/issues/215

Test to test publish performance within a handler context using different transaction modes.

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Common/Scenarios/LoopRunner.cs
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V5.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V6.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.V5.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SendLoop/BaseLoop.cs
src/PerformanceTests/PerformanceTests.sln.DotSettings
src/PerformanceTests/Tests/Categories/Base.cs
src/PerformanceTests/Tests/Categories/SagasFixture.cs
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Utils/TaskHelper.cs

Saga update runner

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/Program.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Common/Scenarios/LoopRunner.cs
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V5.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V6.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.V5.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SendLoop/BaseLoop.cs
src/PerformanceTests/PerformanceTests.sln.DotSettings
src/PerformanceTests/Persistence.V6.InMemory/InMemoryProfile.cs
src/PerformanceTests/Persistence.V6.InMemory/Persistence.V6.InMemory.csproj
src/PerformanceTests/Persistence.V6.NHibernate.V7/NHibernateProfile.cs
src/PerformanceTests/Tests/Categories/Base.cs
src/PerformanceTests/Tests/Categories/SagasFixture.cs
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Utils/TaskHelper.cs

Batch helper gives different strategies for processing.
Forked from SagaUpdate branch. Required to be merged first.
//cc @dvdstelt @danielmarbach

Batch helper

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/Scenarios/SagaCongestion/SagaCongestionRunner.V5.cs
src/PerformanceTests/Common/Scenarios/SagaCongestion/SagaCongestionRunner.V6.cs
src/PerformanceTests/Common/Scenarios/SagaCongestion/SagaCongestionRunner.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V5.cs
src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/Tests/Categories/SagasFixture.cs
src/PerformanceTests/Utils/Permutations/PermutationParser.cs

Added scenario SagaCongestionRunner. This is a scenario where all messages update the same saga instance. It is a simple saga that is stored as a single row. Each message results in  update.

Saga congestion

---

src/PerformanceTests/Transport.V5.RabbitMQ.V3/Transport.V5.RabbitMQ_v3.csproj
src/PerformanceTests/Transport.V5.RabbitMQ.V3/packages.config

@ramonsmits @dvdstelt please review and merge

Update v5 test to Rabbit 3.5.0 transport

---

src/PerformanceTests/Common/StatisticsUoW.cs
src/PerformanceTests/Utils/Statistics.cs

Refactoring suggested by #160 
Access to statistics also made faster by removing step that also did a null check at each invocation.
The changes look more efficient but I could not measure a repeatable improvement.

Implemented #160, statistics now using Stopwatch. 

---

src/PerformanceTests/Persistence.V5.RavenDB.V3/RavenDBProfile.cs
src/PerformanceTests/Persistence.V6.RavenDB.V4/RavenDBProfile.cs

Resolves issue #214

---

src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus6/App.config

Tweaks 20160928

---

src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/Persistence.V5.RavenDB.V3/Persistence.V5.RavenDB_v3.csproj
src/PerformanceTests/Persistence.V5.RavenDB.V3/packages.config
src/PerformanceTests/Persistence.V6.Azure_v7/Persistence.V6.Azure_v7.csproj
src/PerformanceTests/Persistence.V6.Azure_v7/app.config
src/PerformanceTests/Persistence.V6.Azure_v7/packages.config
src/PerformanceTests/Persistence.V6.RavenDB.V4/Persistence.V6.RavenDB_v4.csproj
src/PerformanceTests/Persistence.V6.RavenDB.V4/packages.config
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/Transport.V6.AzureServiceBus_v7.csproj
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/Transport.V6.AzureStorageQueues_v7.csproj
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/app.config
src/PerformanceTests/Transport.V6.AzureStorageQueues.V7/packages.config

New packages, see individual commits

Packages 20160928

---

src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/Tests/Categories/ConcurrencyFixture.cs
src/PerformanceTests/Tests/Tests.csproj

Performance

---

src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SagaCongestion/SagaCongestionRunner.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/AzureServiceBusProfile.cs
src/PerformanceTests/Transport.V6.RabbitMQ.V4/RabbitMQProfile.cs
src/PerformanceTests/Utils/Permutations/Permutation.cs

PrefetchMultiplier now part of all permutation and prefetch supporting transports configured with this value but also used to calculate the amount of messages needed to seed.

Prefetch Multiplier

---

src/PerformanceTests/ArtifactsParser/App.config
src/PerformanceTests/ArtifactsParser/ArtifactsParser.csproj
src/PerformanceTests/ArtifactsParser/Program.cs
src/PerformanceTests/ArtifactsParser/Properties/AssemblyInfo.cs
src/PerformanceTests/PerformanceTests.sln
src/PerformanceTests/Utils/ScanLogs.cs

Scans all *.log files for statistics, aggregates this to a dictionary, and exports this to a file.

Performance test log parser to csv

---

src/PerformanceTests/Common/Common.Data.projitems
src/PerformanceTests/Common/Program.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Common/Scenarios/PerpetualRunner.cs
src/PerformanceTests/Common/Scenarios/PublishOneOnOne/PublishOneOnOneRunner.cs
src/PerformanceTests/Common/Scenarios/SagaCongestion/SagaCongestionRunner.cs
src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.cs
src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs
src/PerformanceTests/Tests/Categories/RavenDBFixture.cs
src/PerformanceTests/Tests/Categories/SagasFixture.cs
src/PerformanceTests/Utils/ReturnCodes.cs
src/PerformanceTests/Utils/Variables/ConcurrencyLevel.cs

- Stability improvements regarding seeding and post checks
- Refactored never ending scenarios, created a perpetual runner base class for shared logic

Improvements 20160930

---

src/PerformanceTests/Distribution.V5.MsmqDistributor.V5/Distribution.V5.MsmqDistributor.V5.csproj
src/PerformanceTests/Distribution.V5.MsmqDistributor.V5/packages.config
src/PerformanceTests/NServiceBus5/NServiceBus5.csproj
src/PerformanceTests/NServiceBus5/packages.config
src/PerformanceTests/Persistence.V5.Azure_v6/Persistence.V5.Azure_v6.csproj
src/PerformanceTests/Persistence.V5.Azure_v6/packages.config
src/PerformanceTests/Persistence.V5.InMemory.V5/Persistence.V5.InMemory.csproj
src/PerformanceTests/Persistence.V5.InMemory.V5/packages.config
src/PerformanceTests/Persistence.V5.NHibernate.V6/Persistence.V5.NHibernate_v6.csproj
src/PerformanceTests/Persistence.V5.NHibernate.V6/packages.config
src/PerformanceTests/Persistence.V5.RavenDB.V3/Persistence.V5.RavenDB_v3.csproj
src/PerformanceTests/Persistence.V5.RavenDB.V3/packages.config
src/PerformanceTests/Transport.V5.AzureServiceBus.V6/Transport.V5.AzureServiceBus_v6.csproj
src/PerformanceTests/Transport.V5.AzureServiceBus.V6/packages.config
src/PerformanceTests/Transport.V5.AzureStorageQueues.V6/Transport.V5.AzureStorageQueues_v6.csproj
src/PerformanceTests/Transport.V5.AzureStorageQueues.V6/packages.config
src/PerformanceTests/Transport.V5.MSMQ.V5/Transport.V5.MSMQ.csproj
src/PerformanceTests/Transport.V5.MSMQ.V5/packages.config
src/PerformanceTests/Transport.V5.RabbitMQ.V3/Transport.V5.RabbitMQ_v3.csproj
src/PerformanceTests/Transport.V5.RabbitMQ.V3/packages.config
src/PerformanceTests/Transport.V5.SQLServer.V2/Transport.V5.SQLServer_v2.csproj
src/PerformanceTests/Transport.V5.SQLServer.V2/packages.config
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/Transport.V6.AzureServiceBus_v7.csproj
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config

Packages 2016-10-14

---

src/PerformanceTests/Transport.V6.AzureServiceBus.V7/Transport.V6.AzureServiceBus_v7.csproj
src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config

NServiceBus.Azure.Transports.WindowsAzureServiceBus.7.0.2

Packages update

---

src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus6/App.Release.config

Solves #255 
Configuration change to remove dependancy on Splunk during execution of performance tests #255.

Disabled Splunk target so Splunk can be removed from the build server.

---

src/PerformanceTests/readme.md

@timbussmann @dvdstelt Please review if the added guidance is clear or if it needs to be extended.

Doco updates about prerequisites and how do add new projects.

---

src/PerformanceTests/Common/ProfilesExtension.cs
src/PerformanceTests/Common/Program.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.v5.cs
src/PerformanceTests/Common/Scenarios/BaseRunner.v6.cs
src/PerformanceTests/NServiceBus5/App.Local.config
src/PerformanceTests/NServiceBus5/App.Release.config
src/PerformanceTests/NServiceBus5/App.config
src/PerformanceTests/NServiceBus5/NServiceBus5.csproj
src/PerformanceTests/NServiceBus5/packages.config
src/PerformanceTests/NServiceBus6/App.Local.config
src/PerformanceTests/NServiceBus6/App.Release.config
src/PerformanceTests/NServiceBus6/App.config
src/PerformanceTests/NServiceBus6/NServiceBus6.csproj
src/PerformanceTests/NServiceBus6/packages.config
src/PerformanceTests/NServiceBus7/App.Local.config
src/PerformanceTests/NServiceBus7/App.Release.config
src/PerformanceTests/NServiceBus7/App.config
src/PerformanceTests/NServiceBus7/NServiceBus7.csproj
src/PerformanceTests/Persistence.V5.Azure_v6/app.config
src/PerformanceTests/Persistence.V5.RavenDB.V3/app.config
src/PerformanceTests/Persistence.V6.RavenDB.V4/app.config
src/PerformanceTests/Tests/Tests.csproj
src/PerformanceTests/Tests/app.config
src/PerformanceTests/Tests/packages.config
src/PerformanceTests/Utils/AssemblyScanner.cs
src/PerformanceTests/Utils/ConfigurationHelper.cs
src/PerformanceTests/Utils/SessionExtensions.cs
src/PerformanceTests/Utils/Statistics.cs
src/PerformanceTests/Utils/Utils.csproj

Switch from nlog to log4net as log4net supportes netstandard

Switch logging to log4net

---

src/PerformanceTests/Utils/Statistics.cs

To be able to target .net standard, we need to replace our usage of performance counters.
There seem to be other, process relates data about memory usage we might use.
Thoughts @ramonsmits @bording 
(this branch needs to be retargeted once csproj-update has been merged)

Remove perf counters

---

src/PerformanceTests/Utils/Utils.csproj

to a .netstandard compatible version

Update command line parser

---

docs/running-performance-tests-on-net-core.md

document how to run perf tests on Azure

---

src/PerformanceTests/ArtifactsParser/Program.cs
src/PerformanceTests/Common/Scenarios/LoopRunner.cs
src/PerformanceTests/NServiceBus7/App.Debug.config
src/PerformanceTests/NServiceBus7/App.config
src/PerformanceTests/Tests/Categories/AuditOnVsOffFixture.cs
src/PerformanceTests/Tests/Categories/Base.cs
src/PerformanceTests/Tests/Categories/ConcurrencyFixture.cs
src/PerformanceTests/Tests/Categories/DistributorFixture.cs
src/PerformanceTests/Tests/Categories/MsmqFixture.cs
src/PerformanceTests/Tests/Categories/OutboxVsDtcFixture.cs
src/PerformanceTests/Tests/Categories/PersistersFixture.cs
src/PerformanceTests/Tests/Categories/PersistersPublishTransactionModesFixture.cs
src/PerformanceTests/Tests/Categories/PlatformFixture.cs
src/PerformanceTests/Tests/Categories/ResourceUtilizationFixture.cs
src/PerformanceTests/Tests/Categories/SagasFixture.cs
src/PerformanceTests/Tests/Categories/SenderSideFixture.cs
src/PerformanceTests/Tests/Categories/TransactionModesFixture.cs
src/PerformanceTests/Tests/Categories/TransportsFixture.cs
src/PerformanceTests/Transport.V7.RabbitMQ.V5/Transport.V7.RabbitMQ_v5.csproj
src/PerformanceTests/Transport.V7.SQLServer.V4/SqlServerProfile.cs
src/PerformanceTests/Utils/Permutations/Permutations.cs

the test configuration to be used for the performance tests targeting v7

Test configuration

---

src/TransportCompatibilityTests/AmazonSQSV3/AmazonSQSV3.csproj
src/TransportCompatibilityTests/AmazonSQSV3/EndpointFacade.cs
src/TransportCompatibilityTests/AmazonSQSV3/Handler.cs
src/TransportCompatibilityTests/TransportCompatibilityTests.Common/AmazonSQS/AmazonSQSEndpointDefinition.cs
src/TransportCompatibilityTests/TransportCompatibilityTests.Common/AmazonSQS/MessageMapping.cs
src/TransportCompatibilityTests/TransportCompatibilityTests.Common/TransportCompatibilityTests.Common.csproj
src/TransportCompatibilityTests/TransportCompatibilityTests.sln

adds an endpoint using SQS transport v3 for the upcoming sqs backwards compat tests

SQS transport endpoint for NSB.Core v6

---

src/TransportCompatibilityTests/TransportCompatibilityTests/AmazonSQS/Callbacks.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/AmazonSQS/Infrastructure/AmazonSqsContext.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/AmazonSQS/MessageExchangePatterns.cs
src/TransportCompatibilityTests/TransportCompatibilityTests/TransportCompatibilityTests.csproj

adding tests for the SQS transport

add SQS tests
