src/PerformanceTests/Utils/Statistics.cs
Change splunk logging to info so the output is visible by default when running locally.
Connects to #3
=> change default splunk log level to Info

src/PerformanceTests/NServiceBus5/App.Release.config, src/PerformanceTests/NServiceBus5/App.config, src/PerformanceTests/NServiceBus6/App.Release.config, src/PerformanceTests/NServiceBus6/App.config
- Logging WARN and higher to file log in release build
- Timestamps in file log formatted in UTC
- Timestamps removed in Trace output as that records its own timestamps.
=> Logging adjustments

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/GatedPublish/GatedPublishRunner.cs, src/PerformanceTests/Common/Scenarios/GatedSendLocal/GatedSendLocalRunner.cs, src/PerformanceTests/Common/Scenarios/LoopRunner.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs, src/PerformanceTests/Common/Scenarios/SendLoop/BaseLoop.cs, src/PerformanceTests/Common/Scenarios/SendLoop/SendLoop.cs
The current implementation hides away the intent of `ISession` inside the runners. Developer has to figure out how abstract method SendMessage() has to send or publish messages. 
With `ISession` as parameter into the SendMessage method, the intent becomes clear that this object has to be used by developer, creating a new scenario.
=> Improve intent of session

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/GatedPublish/GatedPublishRunner.cs, src/PerformanceTests/Common/Scenarios/GatedSendLocal/GatedSendLocalRunner.cs, src/PerformanceTests/Common/Scenarios/LoopRunner.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs, src/PerformanceTests/Common/Scenarios/SendLoop/BaseLoop.cs, src/PerformanceTests/Common/Scenarios/SendLoop/SendLoop.cs
Minor change that moves a check to see if unicastbus was configured in app.config to be executed earlier. When developers try to config it there, they will be pointed towards a specific interface to be implemented. In the previous version, they already had to implement that interface to be able to see the warning, which is a bit weird.
Note: merge this AFTER session-intent was merged. Sorry for confusion! :)
=> Unicastbus config check

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs, src/PerformanceTests/Common/Scenarios/SendLoop/ParallelForRunner.cs
Using ConfigureAwait(false) has a positive effect in the seed throughput for NServiceBus V6.
V6 benefits from limiting the max degree of parallelism. This does have a small negative impact on V5 performance.
The SeedCount and SeedDuration are now added to the test statistics logging.
=> Added .ConfigureAwait(false) + using MaxDegreeOfParallelism + seed stats

src/NHPersistenceCompatibilityTests/Common/NHibernateConnectionInfo.cs, src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/Database.cs, src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/NHibernatePersistenceTests.cs, src/NHPersistenceCompatibilityTests/PersistenceCompatibilityTests/PersistenceCompatibilityTests.csproj
Cleans the database tables when test starts. This would allow us access the tables (for diagnostics) after a test fails.
=> Cleaning database before test runs

src/PerformanceTests/Persistence.V5.NHibernate.V6/NHibernateProfile.cs, src/PerformanceTests/Persistence.V6.NHibernate.V7/NHibernateProfile.cs
Setup was using incorrect permutation value (Transport) to retrieve connection string, now set to persister.
=> NHibernateProfile setup using wrong permutation value

src/PerformanceTests/Common/Program.cs, src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/LoopRunner.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.V6.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs, src/PerformanceTests/Common/Scenarios/SendLoop/BaseLoop.cs, src/PerformanceTests/Common/Scenarios/SendLoop/ForRunner.cs, src/PerformanceTests/Common/Statistics/StatisticsBehavior.V6.cs
Fixes:
- Loop task initialization was incorrectly storing the factory start new task instead of the embedded loop task.
Refactorings:
- Locations that used `.GetAwaiter().GetResult()` refactored to async
- All await statements extended with `.ConfigureAwait(false)`
=> Performance tests async optimizations

src/PerformanceTests/Common/Program.cs, src/PerformanceTests/Transport.V5.AzureServiceBus.V6/AzureServiceBusProfile.cs
Native pubsub got mis configured due to endpoint name differences between x86 / x64 and pubsub broken in V5 due to unsupported / broken scale out default when not using the azure host.
=> Pubsub issues

src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/ServiceControlApi.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/ServiceControlFactory.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/Sql/SqlScTest.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/SampleTests.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/ServiceControlCompatibilityTests.csproj
Related To https://github.com/Particular/PlatformDevelopment/issues/833
Builds on top of https://github.com/Particular/EndToEnd/pull/146
* Changed the web requests to be async
* Generate the test cases based on the implementations if `ITransportDetails` in the assemblies
* Create an activator `Func<T>` to cater for different types of `ITransportDetails`
Depending on the differences between the versions of the transports, we may need to separate the implementations of the `ITransportDetails` into separate projects and have different ones for each version of the transports. (not in scope for now?)
ping @mikeminutillo @ramonsmits @gbiellem @HEskandari
=> Generate test cases based on implementations found

src/PerformanceTests/NServiceBus5/App.Release.config, src/PerformanceTests/NServiceBus6/App.Release.config, src/PerformanceTests/NServiceBus6/App.config
- Log level set to Info for file logging as a failed test on the build server doesn't give any clue what happened.
- Removed log rule for ASB as this log level issue is resolved.
=> PerfTest Logging configuration

src/PlatformCompatibilityTests/ASB/ASBForwardingTopologyTransportDetails.cs, src/PlatformCompatibilityTests/ASQ/ASQTransportDetails.cs, src/PlatformCompatibilityTests/RabbitMQ/RabbitMqTransportDetails.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/EndpointFactory.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/Msmq/MsmqTransportDetails.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/Infrastructure/ServiceControlTest.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/SuccessfulRetryTests.cs, src/PlatformCompatibilityTests/ServiceControlCompatibilityTests/When_retrying_a_message_and_the_handler_has_a_reply.cs, src/PlatformCompatibilityTests/Sql/MultiInstanceSqlTransportDetails.cs, src/PlatformCompatibilityTests/Sql/Sql.csproj, src/PlatformCompatibilityTests/Sql/SqlTransportDetails.cs, src/PlatformCompatibilityTests/TestFramework/IAcceptEndpointMapping.cs, src/PlatformCompatibilityTests/TestFramework/ITransportDetails.cs, src/PlatformCompatibilityTests/TestFramework/SettingsList.cs, src/PlatformCompatibilityTests/TestFramework/TestFramework.csproj
Each test may now provide a mapping from endpoint name to some kind of tag (in this case I've just used logical server name). It is up to the transport to map that to something useful if it wants to.
Multi-Instance SQL Transport uses the tag to map each endpoint to a specific connection string.
=> Multi-Instance SQL Transport support for platform compatibility tests

src/PerformanceTests/Common/Program.cs
Windows defender not present on Windows Server, must check the returned registry key and power options ignored if an error occurs.
=> Fix for failing build due to Windows Defender check assuming that service is present

src/PerformanceTests/Common/Common.Data.projitems, src/PerformanceTests/Common/OutboxProfile.cs, src/PerformanceTests/Common/Program.cs, src/PerformanceTests/NServiceBus5/App.config, src/PerformanceTests/NServiceBus6/App.config, src/PerformanceTests/Tests/Categories/OutboxVsDtcFixture.cs, src/PerformanceTests/Utils/Permutations/PermutationGenerator.cs
- Fix for Outbox vs DTC fixture, outbox was previously not enabled in permutations
- Filtering Outbox vs DTC fixture permutations, only do DTC and no outbox and no DTC with outbox
- First chance exception and unhandled exception event logging improvement
=> Outbox fix for Outbox vs DTC fixture and logging improvements

src/PerformanceTests/NServiceBus5/App.Local.config, src/PerformanceTests/NServiceBus5/App.config, src/PerformanceTests/NServiceBus6/App.Local.config, src/PerformanceTests/NServiceBus6/App.config
Previously the debug build ran with Info log output. Debug builds are usually ran for resolving issues and debug output as default prevents the need to adjust the log level (developers are lazy...).
=> Debug build now has Debug log output

src/PerformanceTests/Common/Program.cs
Added check to warn if processing scheduling isn't set to backgroundservices (reduces local SQL, Raven and MSMQ performance).
=> Processor scheduling check

src/PerformanceTests/Common/Scenarios/LoopRunner.cs
=> Loop runner now using Parallel.For to prevent sequential processing if persistence implementation isn't async.

src/PerformanceTests/Common/Scenarios/SagaInitiate/SagaInitiateRunner.V5.cs, src/PerformanceTests/Common/Scenarios/SagaInitiate/SagaInitiateRunner.V6.cs, src/PerformanceTests/Common/Scenarios/SagaInitiate/SagaInitiateRunner.cs
SagaInitiateRunner now using Guids to be more compatible with storages like Azure table storage that cannot easily cleanup data. Cleanup instructions on Azure are queued which needs polling and that results in unneeded delays.
Saga class also renamed to reference the intent and aligned the message property with the saga property name.
=> SagaInitiateRunner using guids

src/PerformanceTests/Transport.V6.AzureServiceBus.V7/AzureServiceBusProfile.cs
Default pre-fetch size is 200, applying same formula as present in RabbitMQ as 'PrefetchMultiplier' which default to 3.
=> ASB prefetch calculation based on max concurrency level

src/PerformanceTests/Common/Scenarios/LoopRunner.cs, src/PerformanceTests/Utils/AsyncCountdownEvent.cs, src/PerformanceTests/Utils/Utils.csproj
Removes the TaskFactory usage including the `LongRunning` flag. The long running would not have positive impact on this code. After the first await statement the dedicated background thread would potentially already be gone. Switched to `Task.Run` instead.
Inner send loop was a mixture of Async and Sync blocking calls. Introduced AsyncCountDown event which makes it possible to asynchronously await a batch of messages.
=> Introducing async countdown into loop runner and fixing shutdown proxy wait

src/PerformanceTests/Tests/Categories/Base.cs
Removed killing of process as this is causing issues on the build server. Tests ran after this test result in a System.IO.IOException
```
System.IO.IOException : The process cannot access the file 'C:\BuildAgent\work\fa5f215bc71fc336\perftests\@\Performance\PersistersPublishTransactionModesFixture\PublishOneOnOneRunner\V5~Azure~Transactional~\Newtonsoft.Json.dll' because it is being used by another process.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, …
```
=> Removed killing of test process if running too long

src/PerformanceTests/Tests/Categories/Base.cs, src/PerformanceTests/Tests/Tools/TestEnvironment.cs, src/PerformanceTests/Tests/app.config
- Reverted the killing of the process as that cause files to be locked for access but cloning is now resilient to such temporary issues.
- Duration after which to kill the process is increased to 10 minutes as 150 seconds was too short. Some seed/receive tests required more time due to 'slow' receives.
This resolves the issue on the build server where tests crashed with:
> System.IO.IOException : The process cannot access the file 'C:\BuildAgent\work\fa5f215bc71fc336\perftests\@\Performance\SagasFixture\SagaInitiateRunner\V6~RavenDB~Atomic~Sequential~\Newtonsoft.Json.dll' because it is being used by another process.
=> Made cloning of folders more resilient 

src/PerformanceTests/Common/Scenarios/BaseRunner.cs
Critical errors are now logged, logging is flushed and it is attempted to stop the bus but on any condition will kill the process.
=> Critical error handling

src/PerformanceTests/Common/Common.Data.projitems, src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Shortcut/ShortcutBehavior.cs, src/PerformanceTests/Common/Shortcut/ShortcutFeature.cs, src/PerformanceTests/Common/Statistics/SimpleStatisticsFeature.V5.cs, src/PerformanceTests/Common/Statistics/SimpleStatisticsFeature.V6.cs, src/PerformanceTests/Persistence.V6.RavenDB.V4/RavenDBProfile.cs
Performance tests perform a purge operation first. Not all transports support purge on startup or the purge operation is async. This makes sure that the queue is drained first.
=> Purge and drain

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Shortcut/ShortcutBehavior.cs
Draining during purge operation didn't work properly as messages got processed before the draining could be started due to messages already being received and processed before the endpoint is completely initialized when calling `await Endpoint.Start(configuration)`
=> Resolves bug related to draining messages at start

src/PerformanceTests/NServiceBus7/ConcurrencyProfile.cs, src/PerformanceTests/NServiceBus7/NServiceBus7.csproj
@ramonsmits This is the reason for the major performance regression I noticed in the v7 test results. Looks like the max concurrency wasn't being set properly with the v7 host runner.
=> Fix v7 host by adding ConcurrencyProfile

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/LoopRunner.cs, src/PerformanceTests/Common/Scenarios/PerpetualRunner.cs, src/PerformanceTests/Common/Shortcut/ShortcutFeature.cs, src/PerformanceTests/Transport.V6.MSMQ.V6/MsmqProfile.cs, src/PerformanceTests/Transport.V7.MSMQ_v1/MsmqProfile.cs, src/PerformanceTests/Utils/BatchHelper.cs
Seeding improvements:
- Seeding wasn't purely async on v6 and v7. Now it is, except for MSMQ which overrules the batchhelper with an implementation that uses Task.`Run`.
- Draining was broken on v5 resulted in seeding to never happen.
- Sends during seeding previously resulted in the whole test to fail. Sends are expected to sometimes fail, for example due to throttling or reaching a connection limit. Sends during seeding now allow for some retries to happen including exponential backoff. This results in transports like AmazonSQS and SQL Server to be able to complete the seeding operation.
=> Seeding improvements

src/PerformanceTests/Utils/Utils.csproj
It doesn't seem to cause any compilation issues to remove this import and some of the tests I used for smoke-testing the change also ran without issues.
Maybe @Particular/endtoend-maintainers know why this was added initially?
=> Remove mscoree COM reference

src/PerformanceTests/Utils/AssemblyScanner.cs, src/PerformanceTests/Utils/ConfigurationHelper.cs, src/PerformanceTests/Utils/SessionExtensions.cs, src/PerformanceTests/Utils/Statistics.cs, src/PerformanceTests/Utils/Utils.csproj
GetLogger(string) is not supported by log4net on the netstandard API. Another approach would be to use `GetLogger(Assembly.GetCallingAssembly(), name)`, but I think the typeof approach should work fine as well.
=> Target netstandard in Utils

src/PerformanceTests/Common/Scenarios/GatedSendLocal/GatedSendLocalRunner.cs, src/PerformanceTests/Common/Scenarios/Receive/ReceiveRunner.cs, src/PerformanceTests/Common/Scenarios/SendLocalOneOnOne/SendLocalOneOnOneRunner.cs, src/PerformanceTests/Common/Scenarios/SendLoop/SendLoop.cs, src/PerformanceTests/NServiceBus5/Session.cs, src/PerformanceTests/NServiceBus6/Session.cs, src/PerformanceTests/NServiceBus7/Session.cs, src/PerformanceTests/Scenarios/SagaCongestion/SagaCongestionRunner.cs, src/PerformanceTests/Scenarios/SagaInitiate/SagaInitiateRunner.cs, src/PerformanceTests/Scenarios/SagaUpdate/SagaUpdateRunner.cs, src/PerformanceTests/Utils/ISession.cs
V7 broke SendLocal behavior, not allowed anymore on send-only endpoints and this resulted in a few scenarios to break at runtime as this was used for easily seeding message to 'itself' while not yet processing any message. Seeding now uses the endpoint name as the address and passed via `Send(address, message)`.
=> V7 broke SendLocal behavior, not allowed anymore on send-only endpoints

src/PerformanceTests/Common/PerformanceCounters.cs, src/PerformanceTests/Common/Program.cs, src/PerformanceTests/NServiceBus7/NServiceBus7.csproj
Targeting core directly as this project will create the executing assembly in the tests.
Additional (required) changes:
* Conditionally compile the PerformanceCounters dependency, as this won't work on .net core.
* We cannot call `XmlConfigurator.Configure` directly when targeting the netstandard version of log4net. I'm not sure this is the correct way to do it, but due to missing dependencies, I haven't tested this yet.
* Pulling in the registry dependency when targeting .net core.
=> Target .net core 2.0 in v7 host

src/PerformanceTests/Tests/Tools/PermutationDirectoryResolver.cs, src/PerformanceTests/Tests/Tools/TestEnvironment.cs
as we're already multitargeting, the current file copy mechanism copies files from both targets into the test execution folder, causing weird assembly loading issues.
ping @ramonsmits
=> Fix file copy sources

src/PerformanceTests/Tests/Categories/PlatformFixture.cs
Platform fixture now tests all platforms again using RabbitMQ as that is one of the few transports available, set transaction mode to ReceiveOnly.
=> Platform fixture now tests all platforms again using RabbitMQ

.gitignore, src/PerformanceTests/NServiceBus5/NServiceBus5.csproj, src/PerformanceTests/NServiceBus6/NServiceBus6.csproj, src/PerformanceTests/NServiceBus7/NServiceBus7.csproj, src/PerformanceTests/readme.md
Host for v7 contained a double entry which is removed. The host projects now link to a connection string file outside of the repo. This way we can perform a future build on linux too but custom connection string values wil not indicate a change in the repo.
=> Connectionstrings outside repo

src/PerformanceTests/Common/Scenarios/BaseRunner.cs, src/PerformanceTests/Common/Scenarios/LoopRunner.cs
Based on feedback by @timbussmann that asked a question about the following log entries and thought that after the batch size increment only a single batch of messages was seeded.
```
2017-11-22 09:04:44,212|INFO|11|BaseRunner|Increasing seed batch size to   2,048 as sending took   1,884ms which is less then 2,500ms
2017-11-22 09:05:08,066|INFO|18|BaseRunner|Done seeding, seeded 13,824 messages, 516.3 msg/s
```
=> Logging progress of seeding of invidual batches

src/PerformanceTests/Common/EnvironmentStats.cs, src/PerformanceTests/Common/Program.cs, src/PerformanceTests/Common/Statistics/SimpleStatisticsFeature.V6.cs, src/PerformanceTests/NServiceBus7/NServiceBus7.csproj, src/PerformanceTests/Tests/Categories/SqlTransportFixture.cs, src/PerformanceTests/Transport.V5.SQLServer.V2/SqlServerProfile.cs, src/PerformanceTests/Transport.V6.SQLServer.V3/SqlServerProfile.cs, src/PerformanceTests/Transport.V7.SQLServer.V4/SqlServerProfile.cs
relates to https://github.com/Particular/DotNetCoreLaunch/issues/71
addresses the non unix compatible APIs used in the Host of the performance tests as shown in https://github.com/Particular/EndToEnd/pull/300
Kept all the logic in place in case the .net core application runs on windows.
=> NSB 7 Host Unix compatibility

src/TransportCompatibilityTests/AmazonSQSV3/AmazonSQSV3.csproj, src/TransportCompatibilityTests/AmazonSQSV3/EndpointFacade.cs, src/TransportCompatibilityTests/AmazonSQSV4/AmazonSQSV4.csproj, src/TransportCompatibilityTests/AmazonSQSV4/EndpointFacade.cs, src/TransportCompatibilityTests/AmazonSQSV4/Handler.cs, src/TransportCompatibilityTests/TransportCompatibilityTests.Common/AmazonSQS/AmazonSQSEndpointDefinition.cs, src/TransportCompatibilityTests/TransportCompatibilityTests.Common/Conventions.cs, src/TransportCompatibilityTests/TransportCompatibilityTests.sln, src/TransportCompatibilityTests/TransportCompatibilityTests/AmazonSQS/Callbacks.cs, src/TransportCompatibilityTests/TransportCompatibilityTests/AmazonSQS/MessageExchangePatterns.cs
* Changed the target to `net452` since the main test project targets `net452`
* Hard-coded the assembly path convention to look for `net452`. This and the above needs to be solved properly when we want to be able to run on .NET core
* Minor fixes to the abstraction types
* Removed (for now) version 4 from the list
* Hard-coded (for now) the region to `us-east-1`
=> Get the tests to run
